bookmark/urls.py
from django.urls import path
from .views import BookmarkList,BookmarkCreate,BookmarkDelete,BookmarkDetail,BookmarkUpdate

app_name='bookmark'

urlpatterns=[
    path("create/",BookmarkCreate.as_view(),name='create'),
    path("delete/<int:pk>",BookmarkDelete.as_view(),name='delete'),
    path("update/<int:pk>",BookmarkUpdate.as_view(),name='update'),
    path("detail/<int:pk>",BookmarkDetail.as_view(),name='detail'),
    path("",BookmarkList.as_view(),name='index'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('bookmark.urls'))
]

bookmark/models.py
from django.db import models

# Create your models here.
class Bookmark(models.Model):
    site_name=models.CharField(max_length=30)
    url=models.URLField()
    contents=models.TextField(blank=True)
    created=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "사이트명 : "+self.site_name+", URL : "+self.url

    class Meta:
        ordering=["-created"]

bookmark/views.py
from django.shortcuts import render
from .models import Bookmark
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.detail import DetailView
# Create your views here.


class BookmarkList(ListView):
    model=Bookmark

class BookmarkCreate(CreateView):
    model=Bookmark
    fields=['site_name','url','contents']
    template_name_suffix='_create'
    success_url='/'


class BookmarkUpdate(UpdateView):
    model = Bookmark
    fields = ['site_name', 'url', 'contents']
    template_name_suffix = '_update'
    success_url = '/'

class BookmarkDelete(DeleteView):
    model = Bookmark
    template_name_suffix = '_delete'
    success_url = '/'


class BookmarkDetail(DetailView):
    model = Bookmark
    template_name_suffix = '_detail'

bookmark/templates/bookmark/bookmark_create.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-8 col-md-4">
        <div class="alert alert-primar" role="alert">
            모든 부분을 다 채워 넣어주세요!
        </div>
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Create">
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

bookmark/templates/bookmark/bookmark_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="alert alert-primary" role="alert">
    진짜로 {{object.site_name}}을(를) 지우실 건가요?
</div>
<form action="" method ="">
    {% csrf_token%}
    <input type="submit" vlaue="Delete OK">
</form>
{% endblock %}

bookmark/templates/bookmark/bookmark_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-8 col-md-4">
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">{{object.site_name}}></h5>
                <h6 class="card-subtitle mb-2 text-muted"><a href="{{object.url}}"></a>{{object.url}}</h6>
                <p class="card-text">{{ object.contencts }}</p>
                <a href="{% url 'bookmark:update' object.id %}" class="card-link">수정</a>
                <a href="{% url 'bookmark:delete' object.id %}" class="card-link">삭제</a>
            </div>
        </div>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

bookmark/templates/bookmark/bookmark_list.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-10 col-xl-12 col-md-2">
        <table class="table">
            <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">사이트명</th>
                <th scope="col">URL</th>
                <th scope="col">수정</th>
                <th scope="col">삭제</th>
            </tr>
            </thead>
            <tbody>
            {% for object in object_list %}
            <tr>
                <td>{{object.id}}</td>
                <td>
                    <a href="{% url 'bookmark:detail' object.id %}">
                        {{ object.site_name}}
                    </a>
                </td>
                <td>
                    <a href="{{ object.url }}">
                        {{ object.url}}
                    </a>
                </td>
                <td><a href="{% url 'bookmark:update' object.id %}">수정</a>
                <td><a href="{% url 'bookmark:delete' object.id %}">삭제</a></td>
            </tr>
            {% endfor %}

            <a href="{% url 'bookmark:create' %}" class="btn btn-primary">북마크 추가</a>
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

bookmark/templates/bookmark/bookmark_update.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-8 col-md-4">
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Create">
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}